services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yakutsk"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - PROD_URL=${PROD_URL}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
  frontend:
    build: 
      context: ./web
      args:
        - VITE_BACKEND_URL=${PROD_BACKEND_URL}
    ports:
      - "9000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
